# Generated by Django 4.0.3 on 2022-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=250)),
                ('PRICE', models.IntegerField()),
                ('buildingType', models.CharField(choices=[('C', 'Condo'), ('T', 'Townhouse'), ('S', 'Semi-Detached'), ('H', 'House')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('licenseNumber', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('isAgent', models.BooleanField(default=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
