# Generated by Django 4.0.2 on 2022-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='country',
            new_name='province',
        ),
    ]
