# Generated by Django 4.0.2 on 2022-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blurb',
            field=models.CharField(default='blurb', max_length=500),
            preserve_default=False,
        ),
    ]
