# Generated by Django 4.0.2 on 2022-04-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('real_estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.realestate')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(to='main_app.Bookmark'),
        ),
    ]
