# Generated by Django 4.0.2 on 2022-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.CharField(default='Lorem Ipsum', max_length=2500),
            preserve_default=False,
        ),
    ]
