# Generated by Django 4.0.2 on 2022-04-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_realestate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='isPublished',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
