# Generated by Django 4.0.2 on 2022-04-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_country_realestate_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='parkingSpots',
        ),
        migrations.AddField(
            model_name='realestate',
            name='parking',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='buildingType',
            field=models.CharField(blank=True, choices=[('C', 'Condo'), ('T', 'Townhouse'), ('S', 'Semi-Detached'), ('H', 'House')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='province',
            field=models.CharField(choices=[('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Nova Scotia', 'Nova Scotia'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Quebec', 'Quebec'), ('Winnipeg', 'Winnipeg'), ('Saskatchewan', 'Saskatchewan'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Yukon', 'Yukon'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut')], default=('Ontario', 'Ontario'), max_length=50),
        ),
    ]
