# Generated by Django 4.0.3 on 2022-04-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='profiles',
            field=models.ManyToManyField(to='main_app.profile'),
        ),
    ]
