# Generated by Django 4.0.2 on 2022-04-01 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_realestate_parkingspots_realestate_parking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='closingDate',
            field=models.DateField(default=505.5, verbose_name='Closing Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realestate',
            name='buildingType',
            field=models.CharField(choices=[('C', 'Condo'), ('T', 'Townhouse'), ('S', 'Semi-Detached'), ('H', 'House')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='listingDate',
            field=models.DateField(default=datetime.date(2022, 4, 1), verbose_name='Listing Date'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='parking',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='province',
            field=models.CharField(choices=[('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Nova Scotia', 'Nova Scotia'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Quebec', 'Quebec'), ('Winnipeg', 'Winnipeg'), ('Saskatchewan', 'Saskatchewan'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Yukon', 'Yukon'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut')], default='Ontario', max_length=50),
        ),
    ]
