# Generated by Django 4.0.3 on 2022-04-01 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_userprofile_id_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
