# Generated by Django 4.0.2 on 2022-04-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_realestate_closingdate_alter_realestate_buildingtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='listingDate',
            field=models.DateField(default='2022-04-01', verbose_name='Listing Date'),
        ),
    ]
