# Generated by Django 4.0.2 on 2022-04-01 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_realestate_listingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='listingDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Listing Date'),
        ),
    ]
