# Generated by Django 4.0.2 on 2022-04-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_photo_listingphoto_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
