# Generated by Django 4.0.2 on 2022-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_realestate_listingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='listingDate',
            field=models.DateField(verbose_name='Listing Date'),
        ),
    ]
