# Generated by Django 4.0.2 on 2022-04-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_realestate_listingdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='closingDate',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='listingDate',
        ),
    ]
